#common基础配置
server:
    port: 8081
    #servlet:
      #context-path: /admin
spring:
    resources:
      cache:
        #period: 1d
        cachecontrol:
          max-age: 1d
    datasource:
        name: adminPrdEnv
        url: jdbc:mysql://127.0.0.1/carp?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Admin123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,slf4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        logSlowSql: true
        allow: 127.0.0.1
    freemarker:
        template-loader-path: classpath:/freemarker/
        suffix: .ftl
        cache: false
        order: 1
        contentType: text/html;charset=utf-8
        requestContextAttribute: rc
        exposeSpringMacroHelpers: true
        settings:
          auto_import: /layout/layout.ftl as layout
        prefer-file-system-access: false
    #jpa自动生成sql
    jpa:
      show-sql: true
      properties:
        hibernate:
          id:
            new_generator_mappings: false
        javax:
         persistence:
           schema-generation:
            create-source:  metadata
            scripts:
              action: create
              create-target: carp_reate.sql
  #flyway配置
    flyway:
      enabled: false
#metrics
management:
  endpoints:
    web:
      exposure:
        include:  info,health,metrics
#webssh config
webssh:
  allowedUsers: root:CarpAdmin@123!:%
#carp配置
carp:
  config:
  #默认页面的title
    default-title: "Carp Demo"
    #项目版本号
    version:  "V0.4.0"
    #版本状态
    version-status: "SNAPSHOT"
    #项目名称,各种地方用到
    project-name: "Carp"
    #登录页面的字
    login-text: "login"
    login-user-name: "admin"
    login-user-password:  "admin123"
    #是否显示导航上没有实现的链接
    show-unused-icons:  true
    expose-static-classes: []
    expose-bean-names:  ["carpConfig"]
    theme: "adminLTE"
    #theme: "huiAdmin"